[project]
name = "cpsc491-wetravel"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic[email]>=2.13.5",
    "pwdlib[argon2]>=0.3.1",
    "PyJWT>=2.14.0",
    "sqlalchemy>=2.0.52",
    "psycopg[binary]>=3.3.5",
    "alembic>=1.20.0",
    "python-dotenv>=1.2.3",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
]
